version: "3.8"

services:
  mongo-rs-1:
    image: mongo:latest
    container_name: mongo-rs-1
    hostname: mongo-rs-1
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    ports:
      - 30001:30001
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 30001 --quiet || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-rs-2:
    image: mongo:latest
    container_name: mongo-rs-2
    hostname: mongo-rs-2
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    ports:
      - 30002:30002
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 30002 --quiet || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-rs-3:
    image: mongo:latest
    container_name: mongo-rs-3
    hostname: mongo-rs-3
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    ports:
      - 30003:30003
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 30003 --quiet || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  init-replica-set:
    image: mongo:latest
    container_name: init-replica-set
    depends_on:
      mongo-rs-1:
        condition: service_healthy
      mongo-rs-2:
        condition: service_healthy
      mongo-rs-3:
        condition: service_healthy
    command: >
      bash -c "
      echo 'Initializing replica set...';
      mongosh --host mongo-rs-1 --port 30001 --eval '
        rs.initiate(
          {
            _id: \"my-replica-set\",
            version: 1,
            members: [
              {_id: 0, host: \"mongo-rs-1:30001\", priority: 2},
              {_id: 1, host: \"mongo-rs-2:30002\", priority: 1},
              {_id: 2, host: \"mongo-rs-3:30003\", priority: 1}
            ]
          }
        )
      ';
      
      echo 'Waiting for replica set to be fully initialized...';
      until mongosh --host mongo-rs-1 --port 30001 --eval 'rs.status().ok' --quiet; do
        sleep 1;
      done;
      "